# Import

In [64]:
# %pip install pandas
import pandas as pd

# Load

In [65]:
df = pd.read_csv("eurofxref.csv")
df_hist = pd.read_csv("eurofxref-hist.csv")
df_hist.head()

,Date,USD,JPY,BGN,CYP,CZK,DKK,EEK,GBP,HUF,...,INR,KRW,MXN,MYR,NZD,PHP,SGD,THB,ZAR,Unnamed: 42
0,2026-02-20,1.1767,182.63,NaN,NaN,24.241,7.4716,NaN,0.8728,379.65,...,107.0155,1705.81,20.2402,4.5927,1.9763,68.428,1.4931,36.719,18.9417,NaN
1,2026-02-19,1.1753,182.05,NaN,NaN,24.245,7.4717,NaN,0.8738,379.73,...,107.1830,1703.81,20.3086,4.5937,1.9728,68.225,1.4916,36.722,19.0620,NaN
2,2026-02-18,1.1845,181.99,NaN,NaN,24.256,7.4714,NaN,0.8724,378.23,...,107.4250,1712.66,20.2709,4.6196,1.9730,68.551,1.4971,37.016,18.9794,NaN
3,2026-02-17,1.1826,181.06,NaN,NaN,24.276,7.4706,NaN,0.8733,378.43,...,107.2565,1709.83,20.3572,4.6121,1.9623,68.395,1.4946,37.021,19.0320,NaN
4,2026-02-16,1.1855,181.79,NaN,NaN,24.259,7.4707,NaN,0.8690,377.13,...,107.5625,1708.80,20.3378,4.6235,1.9623,68.722,1.4962,36.863,18.9092,NaN

In [66]:
df.head()

,Date,USD,JPY,CZK,DKK,GBP,HUF,PLN,RON,SEK,...,INR,KRW,MXN,MYR,NZD,PHP,SGD,THB,ZAR,
0,20 February 2026,1.1767,182.63,24.241,7.4716,0.8728,379.65,4.2238,5.0978,10.6745,...,107.0155,1705.81,20.2402,4.5927,1.9763,68.428,1.4931,36.719,18.9417,

# Selecting only USD, SEK, GBP, and JPY

In [67]:
data = ["USD", "SEK", "GBP", "JPY"]
df_curr = df_hist[data]
df_curr.head()

      USD      SEK     GBP     JPY
0  1.1767  10.6745  0.8728  182.63
1  1.1753  10.6915  0.8738  182.05
2  1.1845  10.6160  0.8724  181.99
3  1.1826  10.6480  0.8733  181.06
4  1.1855  10.6205  0.8690  181.79

# Data Cleaning

In [68]:
df_curr.fillna(0, inplace=True)
df_curr.isnull().sum()

C:\Users\artjo\AppData\Local\Temp\ipykernel_12040\817112916.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_curr.fillna(0, inplace=True)

USD    0
SEK    0
GBP    0
JPY    0
dtype: int64

# Calculating rate mean

In [69]:
df_curr_means = df_curr.mean()

# Creating another dataframe for final values

In [70]:
# https://stackoverflow.com/questions/46276637/melt-and-find-average-counts-in-a-pandas-dataframe
# https://stackoverflow.com/questions/24216425/adding-a-new-pandas-column-with-mapped-value-from-a-dictionary
df_final = df_curr.iloc[:, :-1].melt(var_name="Currency Code", value_name="Rate").sort_values("Currency Code").reset_index(drop=True)
df_final["Mean Rate"] = df_final["Currency Code"].map(df_curr_means)
df_final

      Currency Code     Rate  Mean Rate
0               GBP  0.71110   0.784852
1               GBP  0.85290   0.784852
2               GBP  0.85090   0.784852
3               GBP  0.85315   0.784852
4               GBP  0.86330   0.784852
...             ...      ...        ...
20842           USD  1.47920   1.182289
20843           USD  1.46620   1.182289
20844           USD  1.46800   1.182289
20845           USD  1.46630   1.182289
20846           USD  1.17670   1.182289

[20847 rows x 3 columns]

# Loading to markdown

In [71]:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html
df_final.to_markdown("exchange_rates.md", index=False)